SQLPLUS /NOLOG
CONNECT PROYECTO_IS/123
-- 
TRUNCATE TABLE ASIGNACION_TREN;
TRUNCATE TABLE HORARIO;
TRUNCATE TABLE RUTA_DETALLE;
TRUNCATE TABLE RUTA;
TRUNCATE TABLE ESTACION;
TRUNCATE TABLE TREN;

---EStaciones
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (1, 'Observatorio');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (2, 'Juanacatlan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (3, 'Chapultepec');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (4, 'Insurgentes');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (5, 'Cuauhtemoc');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (6, 'Balderas');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (7, 'Salto del Agua');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (8, 'Isabel la Catolica');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (9, 'Pino Suarez');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (10, 'Merced');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (11, 'Candelaria');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (12, 'San Lorenzo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (13, 'Moctezuma');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (14, 'Balbuena');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (15, 'Blvd. Pto. Aereo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (16, 'Gomez Farias');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (17, 'Zaragoza');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (18, 'Pantitlan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (19, 'El Rosario');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (20, 'Tezozomoc');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (21, 'Azcapotzalco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (22, 'Ferreria');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (23, 'Norte 45');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (24, 'Vallejo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (25, 'Instituto del Petroleo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (26, 'Lindavista');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (27, 'Deportivo 18 de Marzo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (28, 'La Villa - Basilica');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (29, 'Martin Carrera');

INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (30, 'Tacubaya');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (31, 'Sevilla');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (32, 'San Lazaro');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (33, 'Boulevard Puerto Aereo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (34, 'Cuatro Caminos');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (35, 'Panteones');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (36, 'Tacuba');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (37, 'Cuitlahuac');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (38, 'Popotla');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (39, 'Colegio Militar');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (40, 'Normal');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (41, 'San Cosme');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (42, 'Revolucion');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (43, 'Hidalgo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (44, 'Bellas Artes');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (45, 'Allende');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (46, 'Zocalo-Tenochtitlan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (47, 'San Antonio Abad');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (48, 'Chabacano');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (49, 'Viaducto');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (50, 'Xola');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (51, 'Villa de Cortes');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (52, 'Nativitas');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (53, 'Portales');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (54, 'Ermita');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (55, 'General Anaya');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (56, 'TasqueÃ±a');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (57, 'Indios Verdes');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (58, 'Potrero');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (59, 'La Raza');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (60, 'Tlatelolco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (61, 'Guerrero');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (62, 'Juarez');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (63, 'NiÃ±os Heroes');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (64, 'Hospital General');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (65, 'Centro Medico');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (66, 'Etiopia-Plaza de la Transparencia');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (67, 'Eugenia');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (68, 'Division del Norte');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (69, 'Zapata');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (70, 'Coyoacan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (71, 'Viveros-Derechos humanos');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (72, 'Miguel Ãngel de Quevedo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (73, 'Copilco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (74, 'Universidad');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (75, 'Talisman');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (76, 'Bondojito');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (77, 'Consulado');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (78, 'Canal del Norte');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (79, 'Morelos');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (80, 'Fray Servando');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (81, 'Jamaica');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (82, 'Santa Anita');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (83, 'Hangares');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (84, 'Terminal Aerea');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (85, 'Oceania');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (86, 'Aragon');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (87, 'Eduardo Molina');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (88, 'Valle Gomez');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (89, 'Misterios');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (90, 'Autobuses del Norte');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (91, 'Politecnico');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (92, 'La Villa-Basilica');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (93, 'Aquiles Serdan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (94, 'Camarones');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (95, 'Refineria');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (96, 'San Joaquin');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (97, 'Polanco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (98, 'Auditorio');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (99, 'Constituyentes');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (100, 'San Pedro de los Pinos');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (101, 'San Antonio');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (102, 'Mixcoac');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (103, 'Barranca del Muerto');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (104, 'Garibaldi-Lagunilla');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (105, 'San Juan de Letran');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (106, 'Doctores');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (107, 'Obrera');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (108, 'La Viga');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (109, 'Coyuya');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (110, 'Iztacalco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (111, 'Apatlaco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (112, 'Aculco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (113, 'Escuadron 201');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (114, 'Atlalilco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (115, 'Iztapalapa');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (116, 'Cerro de la Estrella');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (117, 'UAM-I');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (118, 'Constitucion de 1917');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (119, 'Patriotismo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (120, 'Chilpancingo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (121, 'Lazaro Cardenas');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (122, 'Mixiuhca');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (123, 'Velodromo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (124, 'Ciudad Deportiva');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (125, 'Puebla');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (126, 'Agricola Oriental');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (127, 'Canal de San Juan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (128, 'Tepalcates');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (129, 'Guelatao');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (130, 'PeÃ±on Viejo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (131, 'Acatitla');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (132, 'Santa Marta');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (133, 'Los Reyes');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (134, 'La Paz');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (135, 'Ciudad Azteca');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (136, 'Plaza Aragon');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (137, 'Olimpica');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (138, 'Ecatepec');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (139, 'Muzquiz');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (140, 'Rio de los Remedios');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (141, 'Impulsora');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (142, 'Nezahualcoyotl');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (143, 'Villa de Aragon');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (144, 'Bosque de Aragon');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (145, 'Deportivo Oceania');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (146, 'Romero Rubio');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (147, 'Ricardo Flores Magon');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (148, 'Tepito');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (149, 'Lagunilla');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (150, 'Buenavista');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (151, 'Insurgentes Sur');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (152, 'Hospital 20 de Noviembre');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (153, 'Parque de los Venados');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (154, 'Eje Central');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (155, 'Mexicaltzingo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (156, 'Culhuacan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (157, 'San Andres Tomatlan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (158, 'Lomas Estrella');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (159, 'Calle 11');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (160, 'Periferico Oriente');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (161, 'Tezonco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (162, 'Olivos');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (163, 'Nopalera');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (164, 'Zapotitlan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (165, 'Tlaltenco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (166, 'Tlahuac');

-- Línea 1: Pantitlán - Observatorio
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(1,90);
-- Línea 2: Cuatro Caminos - Tasqueña
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(2,80);
-- Línea 3: Indios Verdes - Universidad
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(3,90);
-- Línea 4: Santa Anita - Martín Carrera
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(4,35);
-- Línea 5: Politécnico - Pantitlán
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(5,45);
-- Línea 6: El Rosario - Martín Carrera
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(6,35);
-- Línea 7: El Rosario - Barranca del Muerto
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(7,70);
-- Línea 8: Garibaldi - Constitución de 1917
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(8,55);
-- Línea 9: Pantitlán - Tacubaya
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(9,40);
-- Línea A: Pantitlán - La Paz
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(10,50);
-- Línea B: Ciudad Azteca - Buenavista
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(11,60);
-- Línea 12: Tláhuac - Mixcoac
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(12,60);

---ruta detalle:
-- Ruta 1: Pantitlán - Observatorio
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (1, 1, 1);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (2, 1, 30);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (3, 1, 3);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (4, 1, 31);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (5, 1, 4);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (6, 1, 6);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (7, 1, 7);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (8, 1, 10);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (9, 1, 11);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (10, 1, 13);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (11, 1, 14);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (12, 1, 17);

-- Ruta 2: Cuatro Caminos - Tasqueña
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (13, 2, 34);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (14, 2, 35);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (15, 2, 36);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (16, 2, 38);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (17, 2, 39);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (18, 2, 40);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (19, 2, 41);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (20, 2, 43);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (21, 2, 44);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (22, 2, 45);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (23, 2, 47);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (24, 2, 48);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (25, 2, 49);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (26, 2, 50);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (27, 2, 52);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (28, 2, 53);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (29, 2, 54);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (30, 2, 55);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (31, 2, 56);

-- Ruta 3: Indios Verdes - Universidad
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (32, 3, 57);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (33, 3, 27);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (34, 3, 58);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (35, 3, 59);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (36, 3, 60);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (37, 3, 61);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (38, 3, 43);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (39, 3, 6);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (40, 3, 64);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (41, 3, 67);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (42, 3, 69);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (43, 3, 71);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (44, 3, 72);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (45, 3, 73);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (46, 3, 74);

-- Ruta 4: Santa Anita - Martín Carrera
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (47, 4, 76);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (48, 4, 77);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (49, 4, 78);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (50, 4, 79);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (51, 4, 11);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (52, 4, 80);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (53, 4, 81);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (54, 4, 82);

-- Ruta 5: Politécnico - Pantitlán
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (55, 5, 83);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (56, 5, 87);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (57, 5, 77);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (58, 5, 89);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (59, 5, 59);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (60, 5, 90);

-- Ruta 6: El Rosario - Martín Carrera
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (61, 6, 19);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (62, 6, 21);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (63, 6, 23);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (64, 6, 24);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (65, 6, 26);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (66, 6, 27);

-- Ruta 7: El Rosario - Barranca del Muerto
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (67, 7, 19);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (68, 7, 94);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (69, 7, 36);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (70, 7, 97);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (71, 7, 98);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (72, 7, 99);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (73, 7, 30);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (74, 7, 100);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (75, 7, 101);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (76, 7, 102);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (77, 7, 103);

-- Ruta 8: Garibaldi - Constitución de 1917
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (78, 8, 104);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (79, 8, 44);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (80, 8, 7);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (81, 8, 106);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (82, 8, 107);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (83, 8, 48);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (84, 8, 108);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (85, 8, 82);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (86, 8, 109);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (87, 8, 110);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (88, 8, 111);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (89, 8, 112);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (90, 8, 114);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (91, 8, 115);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (92, 8, 116);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (93, 8, 117);

-- Ruta 9: Pantitlán - Tacubaya
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (94, 9, 30);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (95, 9, 119);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (96, 9, 120);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (97, 9, 48);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (98, 9, 81);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (99, 9, 122);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (100, 9, 124);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (101, 9, 125);

-- Ruta 10: Pantitlán - La Paz
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (102, 10, 127);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (103, 10, 128);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (104, 10, 129);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (105, 10, 131);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (106, 10, 132);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (107, 10, 133);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (108, 10, 134);

-- Ruta 11: Ciudad Azteca - Buenavista
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (109, 11, 135);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (110, 11, 138);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (111, 11, 141);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (112, 11, 146);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (113, 11, 79);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (114, 11, 148);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (115, 11, 149);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (116, 11, 104);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (117, 11, 61);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (118, 11, 150);

-- Ruta 12: Tláhuac - Mixcoac
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (119, 12, 102);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (120, 12, 151);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (121, 12, 152);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (122, 12, 69);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (123, 12, 153);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (124, 12, 154);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (125, 12, 54);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (126, 12, 155);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (127, 12, 114);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (128, 12, 158);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (129, 12, 159);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (130, 12, 161);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (131, 12, 162);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (132, 12, 163);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (133, 12, 165);

----Trenes
-- Trenes ACTIVO
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (1, 'Tren Rápido 1000', 300, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (3, 'Tren Urbano 3000', 200, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (4, 'Tren Metropolitano 4000', 280, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (5, 'Tren Rápido 5000', 300, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (6, 'Tren Express 6000', 260, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (7, 'Tren Urbano 7000', 220, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (8, 'Tren CDMX 8000', 270, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (9, 'Tren Ligero 9000', 240, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (10, 'Tren Ágil 10000', 310, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (11, 'Tren Estrella 11000', 290, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (12, 'Tren Capital 12000', 250, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (13, 'Tren Rápido 13000', 300, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (14, 'Tren Línea 14000', 260, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (15, 'Tren Exprés 15000', 270, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (16, 'Tren Zócalo 16000', 280, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (17, 'Tren Central 17000', 300, 'ACTIVO');

-- Trenes EN MANTENIMIENTO
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (2, 'Tren Express 2000', 250, 'EN MANTENIMIENTO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (18, 'Tren Exprés 18000', 250, 'EN MANTENIMIENTO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (19, 'Tren Norte 19000', 240, 'EN MANTENIMIENTO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (20, 'Tren Reforma 20000', 260, 'EN MANTENIMIENTO');

-- Trenes FUERA DE SERVICIO
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (21, 'Tren Sur 21000', 230, 'FUERA DE SERVICIO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (22, 'Tren Poniente 22000', 250, 'FUERA DE SERVICIO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (23, 'Tren Oriente 23000', 240, 'FUERA DE SERVICIO');


---Horarios:
--INSERT INTO HORARIO (ID_HORARIO, HORA_INICIO, HORA_FIN) VALUES (1, '05:00', '23:00');

-- Línea 1 (Observatorio – Pantitlán)
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (1, TO_DATE('05:00:00', 'HH24:MI:SS'), TO_DATE('05:25:00', 'HH24:MI:SS'));

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (2, TO_DATE('07:00:00', 'HH24:MI:SS'), TO_DATE('07:25:00', 'HH24:MI:SS'));

-- Línea 2 (Cuatro Caminos – Tasqueña)
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (3, TO_DATE('06:00:00', 'HH24:MI:SS'), TO_DATE('07:06:00', 'HH24:MI:SS'));

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (4, TO_DATE('08:00:00', 'HH24:MI:SS'), TO_DATE('09:06:00', 'HH24:MI:SS'));

-- Línea 3 (Indios Verdes – Universidad)
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (5, TO_DATE('05:30:00', 'HH24:MI:SS'), TO_DATE('06:32:00', 'HH24:MI:SS'));

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (6, TO_DATE('07:30:00', 'HH24:MI:SS'), TO_DATE('08:32:00', 'HH24:MI:SS'));

-- Línea 4 (Martín Carrera – Santa Anita)
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (7, TO_DATE('06:00:00', 'HH24:MI:SS'), TO_DATE('06:20:00', 'HH24:MI:SS'));

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (8, TO_DATE('08:00:00', 'HH24:MI:SS'), TO_DATE('08:20:00', 'HH24:MI:SS'));

-- Línea 5 (Pantitlán – Politécnico)
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (9, TO_DATE('05:45:00', 'HH24:MI:SS'), TO_DATE('06:15:00', 'HH24:MI:SS'));

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (10, TO_DATE('07:45:00', 'HH24:MI:SS'), TO_DATE('08:15:00', 'HH24:MI:SS'));

-- Línea 6 (El Rosario – Martín Carrera)
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (11, TO_DATE('06:00:00', 'HH24:MI:SS'), TO_DATE('06:15:00', 'HH24:MI:SS'));
/*
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (12, TO_DATE('08:00:00', 'HH24:MI:SS'), TO_DATE('08:15:00', 'HH24:MI:SS'));*/

-- Línea 7 (El Rosario – Barranca del Muerto)
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (13, TO_DATE('05:30:00', 'HH24:MI:SS'), TO_DATE('06:58:00', 'HH24:MI:SS'));

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (14, TO_DATE('07:30:00', 'HH24:MI:SS'), TO_DATE('08:58:00', 'HH24:MI:SS'));

-- Línea 8 (Garibaldi – Constitución de 1917)
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (15, TO_DATE('06:00:00', 'HH24:MI:SS'), TO_DATE('06:35:00', 'HH24:MI:SS'));

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (16, TO_DATE('08:00:00', 'HH24:MI:SS'), TO_DATE('08:35:00', 'HH24:MI:SS'));

-- Línea 9 (Tacubaya – Pantitlán)
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (17, TO_DATE('05:30:00', 'HH24:MI:SS'), TO_DATE('06:00:00', 'HH24:MI:SS'));

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (18, TO_DATE('07:30:00', 'HH24:MI:SS'), TO_DATE('08:00:00', 'HH24:MI:SS'));

-- Línea 12 (Mixcoac – Tláhuac)
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (19, TO_DATE('06:00:00', 'HH24:MI:SS'), TO_DATE('06:45:00', 'HH24:MI:SS'));

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (20, TO_DATE('08:00:00', 'HH24:MI:SS'), TO_DATE('08:45:00', 'HH24:MI:SS'));

-- Horarios de la tarde
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (21, TO_DATE('13:00:00', 'HH24:MI:SS'), TO_DATE('13:45:00', 'HH24:MI:SS'));

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (22, TO_DATE('15:00:00', 'HH24:MI:SS'), TO_DATE('15:45:00', 'HH24:MI:SS'));

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (23, TO_DATE('17:00:00', 'HH24:MI:SS'), TO_DATE('17:45:00', 'HH24:MI:SS'));

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (24, TO_DATE('19:00:00', 'HH24:MI:SS'), TO_DATE('19:45:00', 'HH24:MI:SS'));

-- Horarios de la noche
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (25, TO_DATE('14:00:00', 'HH24:MI:SS'), TO_DATE('14:50:00', 'HH24:MI:SS'));

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (26, TO_DATE('16:00:00', 'HH24:MI:SS'), TO_DATE('16:50:00', 'HH24:MI:SS'));

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (27, TO_DATE('18:00:00', 'HH24:MI:SS'), TO_DATE('18:50:00', 'HH24:MI:SS'));

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (28, TO_DATE('20:00:00', 'HH24:MI:SS'), TO_DATE('20:50:00', 'HH24:MI:SS'));

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (29, TO_DATE('23:00:00', 'HH24:MI:SS'), TO_DATE('23:50:00', 'HH24:MI:SS'));


-- Asignaciones de trenes a horarios
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (1, 1, 1, 1);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (2, 1, 2, 2);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (4, 1, 4, 4);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (5, 1, 5, 5);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (7, 4, 7, 7);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (8, 4, 8, 8);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (10, 5, 10, 10);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (11, 6, 11, 11);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (13, 7, 1, 13);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (14, 7, 2, 14);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (16, 8, 4, 16);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (17, 3, 5, 17);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (19, 9, 7, 19);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (20, 9, 8, 20);
/* INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (3, 3, 3, 3); */
/* INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (6, 3, 6, 6); */
/* INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (9, 5, 9, 9); */
/* INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (12, 6, 12, 12); */
/* INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (15, 8, 3, 15); */
/* INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (18, 1, 6, 18); */

INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (25, 1, 1, 21);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (26, 3, 2, 22);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (27, 4, 3, 23);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (28, 5, 4, 24);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (29, 6, 5, 25);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (30, 7, 6, 26);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (31, 8, 7, 27);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (32, 9, 8, 28);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (33, 9, 8, 29);

COMMIT;








