--CREACION USUARIO PARA EL PROYECTO DE IS
SQLPLUS /NOLOG
CONN SYS/1234 AS SYSDBA
SET ECHO OFF
SET VERIFY OFF
SELECT instance_name FROM v$instance;
--POR SI NO SIRVE EL COMANDO DE CREAR USUARIO xd
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
DROP USER PROYECTO_IS CASCADE;
CREATE USER PROYECTO_IS IDENTIFIED BY 123;
ALTER USER PROYECTO_IS DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
ALTER USER PROYECTO_IS TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO PROYECTO_IS;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE TO PROYECTO_IS;
GRANT execute ON sys.dbms_stats TO PROYECTO_IS;

--CREACION DE TABLAS
CONN PROYECTO_IS/123

DROP TABLE TREN CASCADE CONSTRAINTS;
DROP TABLE ESTACION CASCADE CONSTRAINTS;
DROP TABLE RUTA CASCADE CONSTRAINTS;
DROP TABLE RUTA_DETALLE CASCADE CONSTRAINTS;
DROP TABLE HORARIO CASCADE CONSTRAINTS;
DROP TABLE ASIGNACION_TREN CASCADE CONSTRAINTS;
DROP TABLE INCIDENCIA CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE HISTORIAL CASCADE CONSTRAINTS;
DROP TRIGGER TRG_ASIGNACION_TREN;
DROP TRIGGER TRG_ORDEN_RUTA_DETALLE;

CREATE TABLE TREN (
    ID_TREN INT CONSTRAINT TREN_PK PRIMARY KEY,
    NOMBRE VARCHAR(50) CONSTRAINT TREN_NOMBRE_NN NOT NULL,
    CAPACIDAD INT CONSTRAINT TREN_CAPACIDAD_NN NOT NULL 
				  CONSTRAINT TREN_CAPACIDAD_CK CHECK (CAPACIDAD > 0),
    ESTADO VARCHAR(20) CONSTRAINT TREN__ESTADO_NN NOT NULL
					   CONSTRAINT TREN_ESTADO_CK CHECK (ESTADO IN ('ACTIVO', 'EN MANTENIMIENTO', 'FUERA DE SERVICIO'))
);
---Se agrego Disponible para difereniciar cuando esta en servicio y cuando no,
CREATE TABLE ESTACION (
    ID_ESTACION INT CONSTRAINT ESTACION_PK PRIMARY KEY,
    NOMBRE VARCHAR(100) CONSTRAINT ESTACION_NOMBRE_NN NOT NULL
);

CREATE TABLE RUTA (
    ID_RUTA INT CONSTRAINT RUTA_PK PRIMARY KEY,
    DURACION_ESTIMADA INT CONSTRAINT RUTA_DURACION_NN NOT NULL 
						  CONSTRAINT RUTA_DURACION_CK CHECK (DURACION_ESTIMADA > 0),
	IMAGEN BLOB
);

CREATE TABLE RUTA_DETALLE (
    ID_RUTA_DETALLE INT CONSTRAINT RUTA_DETALLE_PK PRIMARY KEY,
    ID_RUTA INT CONSTRAINT RUTA_DETALLE_ID_RUTA_NN NOT NULL,
    ID_ESTACION INT CONSTRAINT RUTA_DETALLE_ID_ESTACION_NN NOT NULL,
    ORDEN INT CONSTRAINT RUTA_DETALLE_ORDEN_NN NOT NULL 
			  CONSTRAINT RUTA_DETALLE_ORDEN_CK CHECK (ORDEN > 0),
    CONSTRAINT RUTA_DETALLE_ID_RUTA_FK FOREIGN KEY (ID_RUTA) REFERENCES RUTA(ID_RUTA),
    CONSTRAINT RUTA_DETALLE_ID_ESTACION_FK FOREIGN KEY (ID_ESTACION) REFERENCES ESTACION(ID_ESTACION)
);

--PARA OBTENER ORIGEN Y DESTINO, OSEA INICIO Y FINAL DE UNA RUTA
-- Obtener ORIGEN de una ruta
--SELECT ID_ESTACION 
--FROM RUTA_DETALLE 
--WHERE ID_RUTA = ? 
--ORDER BY ORDEN ASC 
--FETCH FIRST 1 ROWS ONLY;

-- Obtener DESTINO de una ruta
--SELECT ID_ESTACION 
--FROM RUTA_DETALLE 
--WHERE ID_RUTA = ? 
--ORDER BY ORDEN DESC 
--FETCH FIRST 1 ROWS ONLY;

CREATE TABLE HORARIO (
    ID_HORARIO INT CONSTRAINT HORARIO_PK PRIMARY KEY,
    HORA_SALIDA_PROGRAMADA DATE CONSTRAINT HORARIO_SALIDA_PROG_NN NOT NULL,
    HORA_LLEGADA_PROGRAMADA DATE CONSTRAINT HORARIO_LLEGADA_PROG_NN NOT NULL
);

--SALIDA Y LLEGADA REAL PERMITEN NULOS POR QUE EN UN PRINCIPIO ESTARAN VACIOS HASTA QUE
--EL TREN COMIENCE A MOVERSE

--ASI FUNCIONA ESTA TABLA POR QUE NO HAY TIPO DE DATO TIME EN ORACLE xddd
--PARA INSERTAR EN LAS COLUMNAS DE HORA SE CONVIERTE UN STRING CON FORMATO DE HORA A DATE CON TO_DATE
--EL GESTOR AÑADE AUTOMATICAMENTE LA FECHA DEL SISTEMA, PERO ESO NO NOS IMPORTA
--INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA)
--VALUES (1, TO_DATE('08:30:00', 'HH24:MI:SS'), TO_DATE('10:45:00', 'HH24:MI:SS'));

--INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA)
--VALUES (2, TO_DATE('09:15:00', 'HH24:MI:SS'), TO_DATE('11:30:00', 'HH24:MI:SS'));

--Y LUEGO PARA CONSULTARLO SOLAMENTE SE TOMA LA PARTE QUE IMPORTA, QUE ES LA HORA, CON UN TO_CHAR
--SELECT ID_HORARIO,
--       TO_CHAR(HORA_SALIDA_PROGRAMADA, 'HH24:MI:SS') AS HORA_SALIDA_PROGRAMADA,
--       TO_CHAR(HORA_LLEGADA_PROGRAMADA, 'HH24:MI:SS') AS HORA_LLEGADA_PROGRAMADA
--FROM HORARIO;

CREATE TABLE ASIGNACION_TREN (
    ID_ASIGNACION INT CONSTRAINT ASIGNACION_PK PRIMARY KEY,
    HORA_SALIDA_REAL DATE,
    HORA_LLEGADA_REAL DATE,
    ID_TREN INT CONSTRAINT ASIGNACION_ID_TREN_NN NOT NULL,
    ID_RUTA INT CONSTRAINT ASIGNACION_ID_RUTA_NN NOT NULL,
    ID_HORARIO INT CONSTRAINT ASIGNACION_ID_HORARIO_NN NOT NULL,
    CONSTRAINT ASIGNACION_ID_TREN_FK FOREIGN KEY (ID_TREN) REFERENCES TREN(ID_TREN),
    CONSTRAINT ASIGNACION_ID_RUTA_FK FOREIGN KEY (ID_RUTA) REFERENCES RUTA(ID_RUTA),
    CONSTRAINT ASIGNACION_ID_HORARIO_FK FOREIGN KEY (ID_HORARIO) REFERENCES HORARIO(ID_HORARIO)
);

CREATE TABLE INCIDENCIA (
    ID_INCIDENCIA INT CONSTRAINT INCIDENCIA_PK PRIMARY KEY,
    ID_HORARIO INT CONSTRAINT INCIDENCIA_ID_HORARIO_NN NOT NULL,
    TIPO VARCHAR(50) CONSTRAINT INCIDENCIA_TIPO_NN NOT NULL
					 CONSTRAINT INCIDENCIA_TIPO_CK CHECK (TIPO IN ('RETRASO', 'AVERÍA', 'EMERGENCIA')),
    DESCRIPCION VARCHAR2(150) CONSTRAINT INCIDENCIA_DESCRIPCION_NN NOT NULL,
    FECHA_HORA DATE CONSTRAINT INCIDENCIA_FECHA_NN NOT NULL,
    CONSTRAINT INCIDENCIA_ID_HORARIO_FK FOREIGN KEY (ID_HORARIO) REFERENCES HORARIO(ID_HORARIO)
);

-- Crear la tabla USUARIO 
CREATE TABLE USUARIO (
    ID_USUARIO INT CONSTRAINT USUARIO_PK PRIMARY KEY,
    NOMBRE VARCHAR2(50) CONSTRAINT USUARIO_NOMBRE_NN NOT NULL,
    APELLIDO_PATERNO VARCHAR2(50) CONSTRAINT USUARIO_APELLIDO_P_NN NOT NULL,
    APELLIDO_MATERNO VARCHAR2(50) CONSTRAINT USUARIO_APELLIDO_M_NN NOT NULL,
    CONTRASENA VARCHAR2(100) CONSTRAINT USUARIO_CONTRASENA_NN NOT NULL
);

CREATE TABLE HISTORIAL (
    ID_HISTORIAL INT CONSTRAINT HISTORIAL_PK PRIMARY KEY,
    FECHA_REGISTRO DATE DEFAULT SYSDATE CONSTRAINT HISTORIAL_FECHA_NN NOT NULL,
    INFORMACION VARCHAR2(200) CONSTRAINT HISTORIAL_HISTORIAL_NN NOT NULL,
    ID_USUARIO INT CONSTRAINT HISTORIAL_ID_USUARIO_NN NOT NULL,
    ID_HORARIO INT,
    ID_RUTA INT,
    ID_ASIGNACION INT,
    CONSTRAINT HISTORIAL_ID_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT HISTORIAL_ID_HORARIO_FK FOREIGN KEY (ID_HORARIO) REFERENCES HORARIO(ID_HORARIO),
    CONSTRAINT HISTORIAL_ID_RUTA_FK FOREIGN KEY (ID_RUTA) REFERENCES RUTA(ID_RUTA),
    CONSTRAINT HISTORIAL_ID_ASIGNACION_FK FOREIGN KEY (ID_ASIGNACION) REFERENCES ASIGNACION_TREN(ID_ASIGNACION),
    CONSTRAINT HISTORIAL_FKS_CK CHECK (
        (CASE WHEN ID_HORARIO IS NOT NULL THEN 1 ELSE 0 END +
         CASE WHEN ID_RUTA IS NOT NULL THEN 1 ELSE 0 END +
         CASE WHEN ID_ASIGNACION IS NOT NULL THEN 1 ELSE 0 END) = 1
    )
);

INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (1, 'Tren A', 200, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (2, 'Tren B', 150, 'EN MANTENIMIENTO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (3, 'Tren C', 180, 'FUERA DE SERVICIO');

INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (1, 'Estación Central');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (2, 'Estación Norte');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (3, 'Estación Sur');

INSERT INTO RUTA (ID_RUTA, DURACION_ESTIMADA) VALUES (1, 30);
INSERT INTO RUTA (ID_RUTA, DURACION_ESTIMADA) VALUES (2, 45);

INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION, ORDEN) VALUES (1, 1, 1, 1);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION, ORDEN) VALUES (2, 1, 2, 2);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION, ORDEN) VALUES (3, 2, 2, 1);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION, ORDEN) VALUES (4, 2, 3, 2);

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (1, TO_DATE('08:00:00', 'HH24:MI:SS'), TO_DATE('08:30:00', 'HH24:MI:SS'));

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (2, TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('09:45:00', 'HH24:MI:SS'));

INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (1, 1, 1, 1);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (2, 2, 2, 2);

INSERT INTO INCIDENCIA (ID_INCIDENCIA, ID_HORARIO, TIPO, DESCRIPCION, FECHA_HORA) 
VALUES (1, 1, 'RETRASO', 'Retraso por mantenimiento', TO_DATE('2025-03-17 08:15:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO INCIDENCIA (ID_INCIDENCIA, ID_HORARIO, TIPO, DESCRIPCION, FECHA_HORA) 
VALUES (2, 2, 'EMERGENCIA', 'Parada de emergencia por fallas técnicas', TO_DATE('2025-03-17 09:20:00', 'YYYY-MM-DD HH24:MI:SS'));

-- Registro de un horario
INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA_REGISTRO, ID_HORARIO) 
VALUES (1, SYSDATE, 1);

-- Registro de una ruta
INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA_REGISTRO, ID_RUTA) 
VALUES (2, SYSDATE, 2);

-- Registro de una asignación de tren
INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA_REGISTRO, ID_ASIGNACION) 
VALUES (3, SYSDATE, 1);

-- Registro de una incidencia
INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA_REGISTRO, ID_INCIDENCIA) 
VALUES (4, SYSDATE, 2);

SELECT * FROM TREN;
SELECT * FROM ESTACION;
SELECT * FROM RUTA;
SELECT * FROM RUTA_DETALLE;
SELECT ID_HORARIO,
       TO_CHAR(HORA_SALIDA_PROGRAMADA, 'HH24:MI:SS') AS HORA_SALIDA_PROGRAMADA,
       TO_CHAR(HORA_LLEGADA_PROGRAMADA, 'HH24:MI:SS') AS HORA_LLEGADA_PROGRAMADA,
	   TO_CHAR(HORA_SALIDA_REAL, 'HH24:MI:SS') AS HORA_SALIDA_REAL,
       TO_CHAR(HORA_LLEGADA_REAL, 'HH24:MI:SS') AS HORA_LLEGADA_REAL
FROM HORARIO;
SELECT * FROM ASIGNACION_TREN;
SELECT * FROM INCIDENCIA;
SELECT * FROM HISTORIAL;

--NO SE DEBE DE PODER ASIGNAR UN TREN A UNA RUTA SI EL TREN NO TIENE COMO ESTADO 'ACTIVO'
--POR TANTO SE CREA UN TRIGGER PARA MANEJARLO
CREATE OR REPLACE TRIGGER TRG_ASIGNACION_TREN
BEFORE INSERT OR UPDATE ON ASIGNACION_TREN
FOR EACH ROW
DECLARE
    v_estado VARCHAR2(20);
BEGIN
    -- Obtener el estado del tren
    BEGIN
        SELECT ESTADO INTO v_estado
        FROM TREN
        WHERE ID_TREN = :NEW.ID_TREN;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20002, 'El tren con ID ' || :NEW.ID_TREN || ' no existe.');
    END;

    -- Si el estado no es ACTIVO, generar un error
    IF v_estado <> 'ACTIVO' THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se puede asignar un tren que no está en estado ACTIVO.');
    END IF;
END;
/

-- Intentar asignar un tren que no existe (ID_TREN = 99)
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO)
VALUES (5, 99, 1, 1);

-- Intentar asignar un tren EN MANTENIMIENTO (ID_TREN = 2)
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO)
VALUES (6, 2, 1, 1);

-- Intentar asignar un tren ACTIVO (ID_TREN = 1)
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO)
VALUES (7, 1, 1, 1);

--EL VALOR ORDEN EN LA TABLA RUTA_DETALLE SE ASIGNARA AUTOMATICAMENTE CON EL SIGUIENTE TRIGGER
CREATE OR REPLACE TRIGGER TRG_ORDEN_RUTA_DETALLE
BEFORE INSERT ON RUTA_DETALLE
FOR EACH ROW
DECLARE
    v_max_orden INT;
BEGIN
    -- Obtener el orden máximo de la ruta ingresada
    SELECT NVL(MAX(ORDEN), 0) INTO v_max_orden
    FROM RUTA_DETALLE
    WHERE ID_RUTA = :NEW.ID_RUTA;
    
    -- Asignar el siguiente número de orden
    :NEW.ORDEN := v_max_orden + 1;
END;
/


--EJEMPLO DE FUNCIONAMIENTO DEL TRIGGER
TRUNCATE TABLE RUTA_DETALLE;

INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) 
VALUES (1, 1, 1); 
-- Se asigna ORDEN = 1 automáticamente

INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) 
VALUES (2, 1, 2); 
-- Se asigna ORDEN = 2 automáticamente

INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) 
VALUES (3, 1, 3); 
-- Se asigna ORDEN = 3 automáticamente

SELECT *
FROM RUTA_DETALLE;


TRUNCATE TABLE HISTORIAL;
TRUNCATE TABLE INCIDENCIA;
TRUNCATE TABLE ASIGNACION_TREN;
TRUNCATE TABLE HORARIO;
TRUNCATE TABLE RUTA_DETALLE;
TRUNCATE TABLE RUTA;
TRUNCATE TABLE ESTACION;
TRUNCATE TABLE TREN;

SELECT * FROM TREN;
SELECT * FROM ESTACION;
SELECT * FROM RUTA;
SELECT * FROM RUTA_DETALLE;
SELECT ID_HORARIO,
       TO_CHAR(HORA_SALIDA_PROGRAMADA, 'HH24:MI:SS') AS HORA_SALIDA_PROGRAMADA,
       TO_CHAR(HORA_LLEGADA_PROGRAMADA, 'HH24:MI:SS') AS HORA_LLEGADA_PROGRAMADA,
	   TO_CHAR(HORA_SALIDA_REAL, 'HH24:MI:SS') AS HORA_SALIDA_REAL,
       TO_CHAR(HORA_LLEGADA_REAL, 'HH24:MI:SS') AS HORA_LLEGADA_REAL
FROM HORARIO;
SELECT * FROM ASIGNACION_TREN;
SELECT * FROM INCIDENCIA;
SELECT * FROM HISTORIAL;

COMMIT;

--DATOS PARA PROBAR LAS INTERFACES
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (1, 'Tren Rápido 1000', 300, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (2, 'Tren Express 2000', 250, 'EN MANTENIMIENTO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (3, 'Tren Urbano 3000', 200, 'ACTIVO');

--INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (1, 'Estación Central');
--INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (2, 'Estación Norte');
--INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (3, 'Estación Sur');
--INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (4, 'Estación Oeste');
--INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (5, 'Estación Este');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (1, 'Observatorio');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (2, 'Juanacatlan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (3, 'Chapultepec');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (4, 'Insurgentes');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (5, 'Cuauhtemoc');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (6, 'Balderas');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (7, 'Salto del Agua');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (8, 'Isabel la Catolica');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (9, 'Pino Suarez');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (10, 'Merced');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (11, 'Candelaria');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (12, 'San Lorenzo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (13, 'Moctezuma');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (14, 'Balbuena');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (15, 'Blvd. Pto. Aereo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (16, 'Gomez Farias');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (17, 'Zaragoza');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (18, 'Pantitlan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (19, 'El Rosario');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (20, 'Tezozomoc');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (21, 'Azcapotzalco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (22, 'Ferreria');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (23, 'Norte 45');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (24, 'Vallejo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (25, 'Instituto del Petroleo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (26, 'Lindavista');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (27, 'Deportivo 18 de Marzo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (28, 'La Villa - Basilica');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (29, 'Martin Carrera');


INSERT INTO RUTA (ID_RUTA, DURACION_ESTIMADA) VALUES (1, 120);
INSERT INTO RUTA (ID_RUTA, DURACION_ESTIMADA) VALUES (2, 90);
INSERT INTO RUTA (ID_RUTA, DURACION_ESTIMADA) VALUES (3, 120);
INSERT INTO RUTA (ID_RUTA, DURACION_ESTIMADA) VALUES (4, 90);

--INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION, ORDEN) VALUES (1, 1, 1, 1);
--INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION, ORDEN) VALUES (2, 1, 3, 2);
--INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION, ORDEN) VALUES (3, 1, 5, 3);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (1, 1, 1);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (2, 1, 2);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (3, 1, 3);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (4, 1, 4);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (5, 1, 5);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (6, 1, 6);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (7, 1, 7);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (8, 1, 8);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (9, 1, 9);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (10, 1, 10);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (11, 1, 11);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (12, 1, 12);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (13, 1, 13);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (14, 1, 14);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (15, 1, 15);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (16, 1, 16);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (17, 1, 17);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (18, 1, 18);

--INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION, ORDEN) VALUES (4, 2, 2, 1);
--INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION, ORDEN) VALUES (5, 2, 4, 2);
--INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION, ORDEN) VALUES (6, 2, 1, 3);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (19, 2, 19);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (20, 2, 20);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (21, 2, 21);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (22, 2, 22);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (23, 2, 23);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (24, 2, 24);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (25, 2, 25);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (26, 2, 26);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (27, 2, 27);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (28, 2, 28);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (29, 2, 29);

INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (30, 3, 18);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (31, 3, 17);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (32, 3, 16);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (33, 3, 15);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (34, 3, 14);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (35, 3, 13);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (36, 3, 12);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (37, 3, 11);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (38, 3, 10);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (39, 3, 9);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (40, 3, 8);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (41, 3, 7);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (42, 3, 6);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (43, 3, 5);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (44, 3, 4);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (45, 3, 3);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (46, 3, 2);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (47, 3, 1);

INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (48, 4, 29);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (49, 4, 28);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (50, 4, 27);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (51, 4, 26);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (52, 4, 25);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (53, 4, 24);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (54, 4, 23);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (55, 4, 22);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (56, 4, 21);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (57, 4, 20);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (58, 4, 19);

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (1, TO_DATE('08:30:00', 'HH24:MI:SS'), TO_DATE('10:00:00', 'HH24:MI:SS'));

INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (2, TO_DATE('10:15:00', 'HH24:MI:SS'), TO_DATE('12:15:00', 'HH24:MI:SS'));

INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (1, 1, 1, 1);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (2, 3, 2, 2);

INSERT INTO INCIDENCIA (ID_INCIDENCIA, ID_HORARIO, TIPO, DESCRIPCION, FECHA_HORA) 
VALUES (1, 1, 'RETRASO', 'Retraso por mantenimiento en vías', SYSDATE);

INSERT INTO INCIDENCIA (ID_INCIDENCIA, ID_HORARIO, TIPO, DESCRIPCION, FECHA_HORA) 
VALUES (2, 2, 'AVERÍA', 'Falla en el sistema de frenos', SYSDATE);

INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CONTRASENA)
VALUES (1, 'Emiliano', 'Arista', 'Rodriguez', 123);

INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CONTRASENA)
VALUES (2, 'Milton', 'Florencio', 'Arzate', 456);

INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CONTRASENA)
VALUES (3, 'Nery Yael', 'Hernandez', 'Villavicencio', 789);

INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CONTRASENA)
VALUES (4, 'Jesus Fidel', 'Vaca', 'Vilchiz', 123456789);

-- Registro de un horario
INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA_REGISTRO, ID_HORARIO, ID_USUARIO, INFORMACION) 
VALUES (1, SYSDATE, 1, 1, '08:00:00 - 09:30:00');

-- Registro de una ruta
INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA_REGISTRO, ID_RUTA, ID_USUARIO, INFORMACION) 
VALUES (2, SYSDATE, 2, 2, 100);

-- Registro de una asignación de tren
INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA_REGISTRO, ID_ASIGNACION, ID_USUARIO, INFORMACION) 
VALUES (3, SYSDATE, 1, 1, '08:30:36 - 10:01:02');

COMMIT;

SELECT ID_HORARIO,
        TO_CHAR(HORA_SALIDA_PROGRAMADA,'HH24:MI:SS') AS "S.Programada",
         TO_CHAR(HORA_SALIDA_REAL,'HH24:MI:SS')     AS "S.Real",
         TO_CHAR(HORA_llegada_PROGRAMADA,'HH24:MI:SS') AS "L.Programada",
         TO_CHAR(HORA_llegada_REAL,'HH24:MI:SS')       AS "L.Real"
         FROM HORARIO
         ORDER BY 2;

INSERT INTO RUTA (ID_RUTA, DURACION_ESTIMADA) VALUES (55,3);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (59, 55, 4);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (60, 55, 3);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (61, 55, 2);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (62, 55, 1);

COMMIT;
