SQLPLUS /NOLOG
CONNECT PROYECTO_IS/123
-- 
TRUNCATE TABLE HISTORIAL;
TRUNCATE TABLE INCIDENCIA;
TRUNCATE TABLE ASIGNACION_TREN;
TRUNCATE TABLE HORARIO;
TRUNCATE TABLE RUTA_DETALLE;
TRUNCATE TABLE RUTA;
TRUNCATE TABLE ESTACION;
TRUNCATE TABLE TREN;

---EStaciones
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (1, 'Observatorio');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (2, 'Juanacatlan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (3, 'Chapultepec');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (4, 'Insurgentes');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (5, 'Cuauhtemoc');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (6, 'Balderas');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (7, 'Salto del Agua');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (8, 'Isabel la Catolica');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (9, 'Pino Suarez');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (10, 'Merced');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (11, 'Candelaria');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (12, 'San Lorenzo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (13, 'Moctezuma');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (14, 'Balbuena');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (15, 'Blvd. Pto. Aereo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (16, 'Gomez Farias');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (17, 'Zaragoza');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (18, 'Pantitlan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (19, 'El Rosario');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (20, 'Tezozomoc');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (21, 'Azcapotzalco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (22, 'Ferreria');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (23, 'Norte 45');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (24, 'Vallejo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (25, 'Instituto del Petroleo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (26, 'Lindavista');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (27, 'Deportivo 18 de Marzo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (28, 'La Villa - Basilica');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (29, 'Martin Carrera');

INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (30, 'Tacubaya');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (31, 'Sevilla');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (32, 'San Lazaro');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (33, 'Boulevard Puerto Aereo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (34, 'Cuatro Caminos');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (35, 'Panteones');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (36, 'Tacuba');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (37, 'Cuitlahuac');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (38, 'Popotla');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (39, 'Colegio Militar');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (40, 'Normal');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (41, 'San Cosme');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (42, 'Revolucion');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (43, 'Hidalgo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (44, 'Bellas Artes');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (45, 'Allende');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (46, 'Zocalo-Tenochtitlan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (47, 'San Antonio Abad');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (48, 'Chabacano');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (49, 'Viaducto');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (50, 'Xola');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (51, 'Villa de Cortes');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (52, 'Nativitas');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (53, 'Portales');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (54, 'Ermita');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (55, 'General Anaya');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (56, 'TasqueÃ±a');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (57, 'Indios Verdes');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (58, 'Potrero');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (59, 'La Raza');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (60, 'Tlatelolco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (61, 'Guerrero');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (62, 'Juarez');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (63, 'NiÃ±os Heroes');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (64, 'Hospital General');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (65, 'Centro Medico');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (66, 'Etiopia-Plaza de la Transparencia');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (67, 'Eugenia');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (68, 'Division del Norte');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (69, 'Zapata');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (70, 'Coyoacan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (71, 'Viveros-Derechos humanos');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (72, 'Miguel Ãngel de Quevedo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (73, 'Copilco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (74, 'Universidad');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (75, 'Talisman');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (76, 'Bondojito');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (77, 'Consulado');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (78, 'Canal del Norte');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (79, 'Morelos');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (80, 'Fray Servando');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (81, 'Jamaica');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (82, 'Santa Anita');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (83, 'Hangares');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (84, 'Terminal Aerea');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (85, 'Oceania');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (86, 'Aragon');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (87, 'Eduardo Molina');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (88, 'Valle Gomez');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (89, 'Misterios');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (90, 'Autobuses del Norte');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (91, 'Politecnico');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (92, 'La Villa-Basilica');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (93, 'Aquiles Serdan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (94, 'Camarones');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (95, 'Refineria');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (96, 'San Joaquin');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (97, 'Polanco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (98, 'Auditorio');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (99, 'Constituyentes');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (100, 'San Pedro de los Pinos');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (101, 'San Antonio');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (102, 'Mixcoac');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (103, 'Barranca del Muerto');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (104, 'Garibaldi-Lagunilla');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (105, 'San Juan de Letran');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (106, 'Doctores');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (107, 'Obrera');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (108, 'La Viga');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (109, 'Coyuya');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (110, 'Iztacalco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (111, 'Apatlaco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (112, 'Aculco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (113, 'Escuadron 201');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (114, 'Atlalilco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (115, 'Iztapalapa');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (116, 'Cerro de la Estrella');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (117, 'UAM-I');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (118, 'Constitucion de 1917');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (119, 'Patriotismo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (120, 'Chilpancingo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (121, 'Lazaro Cardenas');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (122, 'Mixiuhca');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (123, 'Velodromo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (124, 'Ciudad Deportiva');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (125, 'Puebla');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (126, 'Agricola Oriental');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (127, 'Canal de San Juan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (128, 'Tepalcates');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (129, 'Guelatao');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (130, 'PeÃ±on Viejo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (131, 'Acatitla');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (132, 'Santa Marta');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (133, 'Los Reyes');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (134, 'La Paz');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (135, 'Ciudad Azteca');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (136, 'Plaza Aragon');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (137, 'Olimpica');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (138, 'Ecatepec');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (139, 'Muzquiz');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (140, 'Rio de los Remedios');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (141, 'Impulsora');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (142, 'Nezahualcoyotl');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (143, 'Villa de Aragon');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (144, 'Bosque de Aragon');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (145, 'Deportivo Oceania');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (146, 'Romero Rubio');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (147, 'Ricardo Flores Magon');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (148, 'Tepito');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (149, 'Lagunilla');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (150, 'Buenavista');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (151, 'Insurgentes Sur');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (152, 'Hospital 20 de Noviembre');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (153, 'Parque de los Venados');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (154, 'Eje Central');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (155, 'Mexicaltzingo');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (156, 'Culhuacan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (157, 'San Andres Tomatlan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (158, 'Lomas Estrella');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (159, 'Calle 11');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (160, 'Periferico Oriente');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (161, 'Tezonco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (162, 'Olivos');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (163, 'Nopalera');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (164, 'Zapotitlan');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (165, 'Tlaltenco');
INSERT INTO ESTACION (ID_ESTACION, NOMBRE) VALUES (166, 'Tlahuac');

-- Línea 1: Pantitlán - Observatorio
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(1,90);
-- Línea 2: Cuatro Caminos - Tasqueña
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(2,80);
-- Línea 3: Indios Verdes - Universidad
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(3,90);
-- Línea 4: Santa Anita - Martín Carrera
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(4,35);
-- Línea 5: Politécnico - Pantitlán
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(5,45);
-- Línea 6: El Rosario - Martín Carrera
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(6,35);
-- Línea 7: El Rosario - Barranca del Muerto
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(7,70);
-- Línea 8: Garibaldi - Constitución de 1917
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(8,55);
-- Línea 9: Pantitlán - Tacubaya
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(9,40);
-- Línea A: Pantitlán - La Paz
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(10,50);
-- Línea B: Ciudad Azteca - Buenavista
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(11,60);
-- Línea 12: Tláhuac - Mixcoac
INSERT INTO RUTA(ID_RUTA,DURACION_ESTIMADA)VALUES(12,60);

---ruta detalle:
-- Ruta 1: Pantitlán - Observatorio
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (1, 1, 1);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (2, 1, 30);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (3, 1, 3);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (4, 1, 31);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (5, 1, 4);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (6, 1, 6);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (7, 1, 7);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (8, 1, 10);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (9, 1, 11);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (10, 1, 13);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (11, 1, 14);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (12, 1, 17);

-- Ruta 2: Cuatro Caminos - Tasqueña
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (13, 2, 34);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (14, 2, 35);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (15, 2, 36);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (16, 2, 38);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (17, 2, 39);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (18, 2, 40);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (19, 2, 41);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (20, 2, 43);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (21, 2, 44);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (22, 2, 45);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (23, 2, 47);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (24, 2, 48);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (25, 2, 49);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (26, 2, 50);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (27, 2, 52);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (28, 2, 53);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (29, 2, 54);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (30, 2, 55);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (31, 2, 56);

-- Ruta 3: Indios Verdes - Universidad
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (32, 3, 57);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (33, 3, 27);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (34, 3, 58);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (35, 3, 59);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (36, 3, 60);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (37, 3, 61);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (38, 3, 43);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (39, 3, 6);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (40, 3, 64);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (41, 3, 67);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (42, 3, 69);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (43, 3, 71);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (44, 3, 72);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (45, 3, 73);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (46, 3, 74);

-- Ruta 4: Santa Anita - Martín Carrera
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (47, 4, 76);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (48, 4, 77);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (49, 4, 78);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (50, 4, 79);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (51, 4, 11);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (52, 4, 80);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (53, 4, 81);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (54, 4, 82);

-- Ruta 5: Politécnico - Pantitlán
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (55, 5, 83);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (56, 5, 87);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (57, 5, 77);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (58, 5, 89);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (59, 5, 59);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (60, 5, 90);

-- Ruta 6: El Rosario - Martín Carrera
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (61, 6, 19);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (62, 6, 21);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (63, 6, 23);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (64, 6, 24);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (65, 6, 26);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (66, 6, 27);

-- Ruta 7: El Rosario - Barranca del Muerto
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (67, 7, 19);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (68, 7, 94);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (69, 7, 36);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (70, 7, 97);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (71, 7, 98);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (72, 7, 99);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (73, 7, 30);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (74, 7, 100);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (75, 7, 101);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (76, 7, 102);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (77, 7, 103);

-- Ruta 8: Garibaldi - Constitución de 1917
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (78, 8, 104);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (79, 8, 44);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (80, 8, 7);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (81, 8, 106);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (82, 8, 107);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (83, 8, 48);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (84, 8, 108);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (85, 8, 82);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (86, 8, 109);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (87, 8, 110);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (88, 8, 111);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (89, 8, 112);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (90, 8, 114);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (91, 8, 115);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (92, 8, 116);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (93, 8, 117);

-- Ruta 9: Pantitlán - Tacubaya
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (94, 9, 30);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (95, 9, 119);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (96, 9, 120);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (97, 9, 48);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (98, 9, 81);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (99, 9, 122);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (100, 9, 124);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (101, 9, 125);

-- Ruta 10: Pantitlán - La Paz
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (102, 10, 127);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (103, 10, 128);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (104, 10, 129);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (105, 10, 131);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (106, 10, 132);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (107, 10, 133);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (108, 10, 134);

-- Ruta 11: Ciudad Azteca - Buenavista
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (109, 11, 135);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (110, 11, 138);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (111, 11, 141);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (112, 11, 146);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (113, 11, 79);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (114, 11, 148);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (115, 11, 149);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (116, 11, 104);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (117, 11, 61);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (118, 11, 150);

-- Ruta 12: Tláhuac - Mixcoac
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (119, 12, 102);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (120, 12, 151);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (121, 12, 152);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (122, 12, 69);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (123, 12, 153);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (124, 12, 154);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (125, 12, 54);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (126, 12, 155);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (127, 12, 114);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (128, 12, 158);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (129, 12, 159);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (130, 12, 161);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (131, 12, 162);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (132, 12, 163);
INSERT INTO RUTA_DETALLE (ID_RUTA_DETALLE, ID_RUTA, ID_ESTACION) VALUES (133, 12, 165);

----Trenes
-- Trenes ACTIVO
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (1, 'Tren Rápido 1000', 300, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (3, 'Tren Urbano 3000', 200, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (4, 'Tren Metropolitano 4000', 280, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (5, 'Tren Rápido 5000', 300, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (6, 'Tren Express 6000', 260, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (7, 'Tren Urbano 7000', 220, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (8, 'Tren CDMX 8000', 270, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (9, 'Tren Ligero 9000', 240, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (10, 'Tren Ágil 10000', 310, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (11, 'Tren Estrella 11000', 290, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (12, 'Tren Capital 12000', 250, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (13, 'Tren Rápido 13000', 300, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (14, 'Tren Línea 19000', 260, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (15, 'Tren Exprés 16000', 270, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (16, 'Tren Zócalo 17000', 280, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (17, 'Tren Central 14000', 300, 'ACTIVO');

INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (24, 'Tren Línea 14000', 260, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (25, 'Tren Exprés 15000', 270, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (26, 'Tren Zócalo 16000', 280, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (27, 'Tren Central 17000', 300, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (28, 'Tren Nueva Línea 28000', 240, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (29, 'Tren Nueva Línea 29000', 250, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (30, 'Tren Nueva Línea 30000', 260, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (31, 'Tren Nueva Línea 31000', 270, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (32, 'Tren Nueva Línea 32000', 280, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (33, 'Tren Nueva Línea 33000', 250, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (34, 'Tren Nueva Línea 34000', 260, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (35, 'Tren Nueva Línea 35000', 270, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (36, 'Tren Nueva Línea 36000', 280, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (37, 'Tren Nueva Línea 37000', 240, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (38, 'Tren Nueva Línea 38000', 250, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (39, 'Tren Nueva Línea 39000', 260, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (40, 'Tren Nueva Línea 40000', 270, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (41, 'Tren Nueva Línea 41000', 280, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (42, 'Tren Nueva Línea 42000', 250, 'ACTIVO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (43, 'Tren Nueva Línea 43000', 260, 'ACTIVO');


-- Trenes EN MANTENIMIENTO
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (2, 'Tren Express 2000', 250, 'EN MANTENIMIENTO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (18, 'Tren Exprés 18000', 250, 'EN MANTENIMIENTO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (19, 'Tren Norte 19000', 240, 'EN MANTENIMIENTO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (20, 'Tren Reforma 20000', 260, 'EN MANTENIMIENTO');

-- Trenes FUERA DE SERVICIO
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (21, 'Tren Sur 21000', 230, 'FUERA DE SERVICIO');
INSERT INTO TREN (ID_TREN, NOMBRE, CAPACIDAD, ESTADO) VALUES (22, 'Tren Poniente 22000', 250, 'FUERA DE SERVICIO');

-- HORARIOS POR RUTA, EN FUNCION DE SU DURACION + 30 MINUTOS
-- SALIDAS CADA 30 MINUTOS, DE 5 AM A 9 PM
-- 33 HORARIOS POR RUTA
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (1, TO_DATE('05:00:00', 'HH24:MI:SS'), TO_DATE('06:05:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (2, TO_DATE('05:30:00', 'HH24:MI:SS'), TO_DATE('06:35:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (3, TO_DATE('06:00:00', 'HH24:MI:SS'), TO_DATE('07:05:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (4, TO_DATE('06:30:00', 'HH24:MI:SS'), TO_DATE('07:35:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (5, TO_DATE('07:00:00', 'HH24:MI:SS'), TO_DATE('08:05:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (6, TO_DATE('07:30:00', 'HH24:MI:SS'), TO_DATE('08:35:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (7, TO_DATE('08:00:00', 'HH24:MI:SS'), TO_DATE('09:05:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (8, TO_DATE('08:30:00', 'HH24:MI:SS'), TO_DATE('09:35:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (9, TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('10:05:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (10, TO_DATE('09:30:00', 'HH24:MI:SS'), TO_DATE('10:35:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (11, TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('11:05:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (12, TO_DATE('10:30:00', 'HH24:MI:SS'), TO_DATE('11:35:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (13, TO_DATE('11:00:00', 'HH24:MI:SS'), TO_DATE('12:05:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (14, TO_DATE('11:30:00', 'HH24:MI:SS'), TO_DATE('12:35:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (15, TO_DATE('12:00:00', 'HH24:MI:SS'), TO_DATE('13:05:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (16, TO_DATE('12:30:00', 'HH24:MI:SS'), TO_DATE('13:35:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (17, TO_DATE('13:00:00', 'HH24:MI:SS'), TO_DATE('14:05:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (18, TO_DATE('13:30:00', 'HH24:MI:SS'), TO_DATE('14:35:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (19, TO_DATE('14:00:00', 'HH24:MI:SS'), TO_DATE('15:05:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (20, TO_DATE('14:30:00', 'HH24:MI:SS'), TO_DATE('15:35:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (21, TO_DATE('15:00:00', 'HH24:MI:SS'), TO_DATE('16:05:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (22, TO_DATE('15:30:00', 'HH24:MI:SS'), TO_DATE('16:35:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (23, TO_DATE('16:00:00', 'HH24:MI:SS'), TO_DATE('17:05:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (24, TO_DATE('16:30:00', 'HH24:MI:SS'), TO_DATE('17:35:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (25, TO_DATE('17:00:00', 'HH24:MI:SS'), TO_DATE('18:05:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (26, TO_DATE('17:30:00', 'HH24:MI:SS'), TO_DATE('18:35:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (27, TO_DATE('18:00:00', 'HH24:MI:SS'), TO_DATE('19:05:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (28, TO_DATE('18:30:00', 'HH24:MI:SS'), TO_DATE('19:35:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (29, TO_DATE('19:00:00', 'HH24:MI:SS'), TO_DATE('20:05:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (30, TO_DATE('19:30:00', 'HH24:MI:SS'), TO_DATE('20:35:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (31, TO_DATE('20:00:00', 'HH24:MI:SS'), TO_DATE('21:05:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (32, TO_DATE('20:30:00', 'HH24:MI:SS'), TO_DATE('21:35:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (33, TO_DATE('21:00:00', 'HH24:MI:SS'), TO_DATE('22:05:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (34, TO_DATE('05:00:00', 'HH24:MI:SS'), TO_DATE('06:10:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (35, TO_DATE('05:30:00', 'HH24:MI:SS'), TO_DATE('06:40:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (36, TO_DATE('06:00:00', 'HH24:MI:SS'), TO_DATE('07:10:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (37, TO_DATE('06:30:00', 'HH24:MI:SS'), TO_DATE('07:40:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (38, TO_DATE('07:00:00', 'HH24:MI:SS'), TO_DATE('08:10:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (39, TO_DATE('07:30:00', 'HH24:MI:SS'), TO_DATE('08:40:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (40, TO_DATE('08:00:00', 'HH24:MI:SS'), TO_DATE('09:10:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (41, TO_DATE('08:30:00', 'HH24:MI:SS'), TO_DATE('09:40:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (42, TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('10:10:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (43, TO_DATE('09:30:00', 'HH24:MI:SS'), TO_DATE('10:40:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (44, TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('11:10:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (45, TO_DATE('10:30:00', 'HH24:MI:SS'), TO_DATE('11:40:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (46, TO_DATE('11:00:00', 'HH24:MI:SS'), TO_DATE('12:10:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (47, TO_DATE('11:30:00', 'HH24:MI:SS'), TO_DATE('12:40:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (48, TO_DATE('12:00:00', 'HH24:MI:SS'), TO_DATE('13:10:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (49, TO_DATE('12:30:00', 'HH24:MI:SS'), TO_DATE('13:40:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (50, TO_DATE('13:00:00', 'HH24:MI:SS'), TO_DATE('14:10:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (51, TO_DATE('13:30:00', 'HH24:MI:SS'), TO_DATE('14:40:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (52, TO_DATE('14:00:00', 'HH24:MI:SS'), TO_DATE('15:10:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (53, TO_DATE('14:30:00', 'HH24:MI:SS'), TO_DATE('15:40:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (54, TO_DATE('15:00:00', 'HH24:MI:SS'), TO_DATE('16:10:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (55, TO_DATE('15:30:00', 'HH24:MI:SS'), TO_DATE('16:40:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (56, TO_DATE('16:00:00', 'HH24:MI:SS'), TO_DATE('17:10:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (57, TO_DATE('16:30:00', 'HH24:MI:SS'), TO_DATE('17:40:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (58, TO_DATE('17:00:00', 'HH24:MI:SS'), TO_DATE('18:10:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (59, TO_DATE('17:30:00', 'HH24:MI:SS'), TO_DATE('18:40:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (60, TO_DATE('18:00:00', 'HH24:MI:SS'), TO_DATE('19:10:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (61, TO_DATE('18:30:00', 'HH24:MI:SS'), TO_DATE('19:40:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (62, TO_DATE('19:00:00', 'HH24:MI:SS'), TO_DATE('20:10:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (63, TO_DATE('19:30:00', 'HH24:MI:SS'), TO_DATE('20:40:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (64, TO_DATE('20:00:00', 'HH24:MI:SS'), TO_DATE('21:10:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (65, TO_DATE('20:30:00', 'HH24:MI:SS'), TO_DATE('21:40:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (66, TO_DATE('21:00:00', 'HH24:MI:SS'), TO_DATE('22:10:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (67, TO_DATE('05:00:00', 'HH24:MI:SS'), TO_DATE('06:15:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (68, TO_DATE('05:30:00', 'HH24:MI:SS'), TO_DATE('06:45:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (69, TO_DATE('06:00:00', 'HH24:MI:SS'), TO_DATE('07:15:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (70, TO_DATE('06:30:00', 'HH24:MI:SS'), TO_DATE('07:45:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (71, TO_DATE('07:00:00', 'HH24:MI:SS'), TO_DATE('08:15:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (72, TO_DATE('07:30:00', 'HH24:MI:SS'), TO_DATE('08:45:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (73, TO_DATE('08:00:00', 'HH24:MI:SS'), TO_DATE('09:15:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (74, TO_DATE('08:30:00', 'HH24:MI:SS'), TO_DATE('09:45:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (75, TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('10:15:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (76, TO_DATE('09:30:00', 'HH24:MI:SS'), TO_DATE('10:45:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (77, TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('11:15:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (78, TO_DATE('10:30:00', 'HH24:MI:SS'), TO_DATE('11:45:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (79, TO_DATE('11:00:00', 'HH24:MI:SS'), TO_DATE('12:15:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (80, TO_DATE('11:30:00', 'HH24:MI:SS'), TO_DATE('12:45:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (81, TO_DATE('12:00:00', 'HH24:MI:SS'), TO_DATE('13:15:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (82, TO_DATE('12:30:00', 'HH24:MI:SS'), TO_DATE('13:45:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (83, TO_DATE('13:00:00', 'HH24:MI:SS'), TO_DATE('14:15:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (84, TO_DATE('13:30:00', 'HH24:MI:SS'), TO_DATE('14:45:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (85, TO_DATE('14:00:00', 'HH24:MI:SS'), TO_DATE('15:15:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (86, TO_DATE('14:30:00', 'HH24:MI:SS'), TO_DATE('15:45:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (87, TO_DATE('15:00:00', 'HH24:MI:SS'), TO_DATE('16:15:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (88, TO_DATE('15:30:00', 'HH24:MI:SS'), TO_DATE('16:45:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (89, TO_DATE('16:00:00', 'HH24:MI:SS'), TO_DATE('17:15:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (90, TO_DATE('16:30:00', 'HH24:MI:SS'), TO_DATE('17:45:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (91, TO_DATE('17:00:00', 'HH24:MI:SS'), TO_DATE('18:15:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (92, TO_DATE('17:30:00', 'HH24:MI:SS'), TO_DATE('18:45:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (93, TO_DATE('18:00:00', 'HH24:MI:SS'), TO_DATE('19:15:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (94, TO_DATE('18:30:00', 'HH24:MI:SS'), TO_DATE('19:45:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (95, TO_DATE('19:00:00', 'HH24:MI:SS'), TO_DATE('20:15:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (96, TO_DATE('19:30:00', 'HH24:MI:SS'), TO_DATE('20:45:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (97, TO_DATE('20:00:00', 'HH24:MI:SS'), TO_DATE('21:15:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (98, TO_DATE('20:30:00', 'HH24:MI:SS'), TO_DATE('21:45:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (99, TO_DATE('21:00:00', 'HH24:MI:SS'), TO_DATE('22:15:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (100, TO_DATE('05:00:00', 'HH24:MI:SS'), TO_DATE('06:20:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (101, TO_DATE('05:30:00', 'HH24:MI:SS'), TO_DATE('06:50:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (102, TO_DATE('06:00:00', 'HH24:MI:SS'), TO_DATE('07:20:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (103, TO_DATE('06:30:00', 'HH24:MI:SS'), TO_DATE('07:50:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (104, TO_DATE('07:00:00', 'HH24:MI:SS'), TO_DATE('08:20:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (105, TO_DATE('07:30:00', 'HH24:MI:SS'), TO_DATE('08:50:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (106, TO_DATE('08:00:00', 'HH24:MI:SS'), TO_DATE('09:20:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (107, TO_DATE('08:30:00', 'HH24:MI:SS'), TO_DATE('09:50:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (108, TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('10:20:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (109, TO_DATE('09:30:00', 'HH24:MI:SS'), TO_DATE('10:50:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (110, TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('11:20:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (111, TO_DATE('10:30:00', 'HH24:MI:SS'), TO_DATE('11:50:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (112, TO_DATE('11:00:00', 'HH24:MI:SS'), TO_DATE('12:20:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (113, TO_DATE('11:30:00', 'HH24:MI:SS'), TO_DATE('12:50:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (114, TO_DATE('12:00:00', 'HH24:MI:SS'), TO_DATE('13:20:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (115, TO_DATE('12:30:00', 'HH24:MI:SS'), TO_DATE('13:50:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (116, TO_DATE('13:00:00', 'HH24:MI:SS'), TO_DATE('14:20:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (117, TO_DATE('13:30:00', 'HH24:MI:SS'), TO_DATE('14:50:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (118, TO_DATE('14:00:00', 'HH24:MI:SS'), TO_DATE('15:20:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (119, TO_DATE('14:30:00', 'HH24:MI:SS'), TO_DATE('15:50:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (120, TO_DATE('15:00:00', 'HH24:MI:SS'), TO_DATE('16:20:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (121, TO_DATE('15:30:00', 'HH24:MI:SS'), TO_DATE('16:50:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (122, TO_DATE('16:00:00', 'HH24:MI:SS'), TO_DATE('17:20:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (123, TO_DATE('16:30:00', 'HH24:MI:SS'), TO_DATE('17:50:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (124, TO_DATE('17:00:00', 'HH24:MI:SS'), TO_DATE('18:20:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (125, TO_DATE('17:30:00', 'HH24:MI:SS'), TO_DATE('18:50:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (126, TO_DATE('18:00:00', 'HH24:MI:SS'), TO_DATE('19:20:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (127, TO_DATE('18:30:00', 'HH24:MI:SS'), TO_DATE('19:50:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (128, TO_DATE('19:00:00', 'HH24:MI:SS'), TO_DATE('20:20:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (129, TO_DATE('19:30:00', 'HH24:MI:SS'), TO_DATE('20:50:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (130, TO_DATE('20:00:00', 'HH24:MI:SS'), TO_DATE('21:20:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (131, TO_DATE('20:30:00', 'HH24:MI:SS'), TO_DATE('21:50:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (132, TO_DATE('21:00:00', 'HH24:MI:SS'), TO_DATE('22:20:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (133, TO_DATE('05:00:00', 'HH24:MI:SS'), TO_DATE('06:25:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (134, TO_DATE('05:30:00', 'HH24:MI:SS'), TO_DATE('06:55:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (135, TO_DATE('06:00:00', 'HH24:MI:SS'), TO_DATE('07:25:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (136, TO_DATE('06:30:00', 'HH24:MI:SS'), TO_DATE('07:55:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (137, TO_DATE('07:00:00', 'HH24:MI:SS'), TO_DATE('08:25:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (138, TO_DATE('07:30:00', 'HH24:MI:SS'), TO_DATE('08:55:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (139, TO_DATE('08:00:00', 'HH24:MI:SS'), TO_DATE('09:25:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (140, TO_DATE('08:30:00', 'HH24:MI:SS'), TO_DATE('09:55:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (141, TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('10:25:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (142, TO_DATE('09:30:00', 'HH24:MI:SS'), TO_DATE('10:55:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (143, TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('11:25:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (144, TO_DATE('10:30:00', 'HH24:MI:SS'), TO_DATE('11:55:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (145, TO_DATE('11:00:00', 'HH24:MI:SS'), TO_DATE('12:25:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (146, TO_DATE('11:30:00', 'HH24:MI:SS'), TO_DATE('12:55:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (147, TO_DATE('12:00:00', 'HH24:MI:SS'), TO_DATE('13:25:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (148, TO_DATE('12:30:00', 'HH24:MI:SS'), TO_DATE('13:55:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (149, TO_DATE('13:00:00', 'HH24:MI:SS'), TO_DATE('14:25:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (150, TO_DATE('13:30:00', 'HH24:MI:SS'), TO_DATE('14:55:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (151, TO_DATE('14:00:00', 'HH24:MI:SS'), TO_DATE('15:25:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (152, TO_DATE('14:30:00', 'HH24:MI:SS'), TO_DATE('15:55:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (153, TO_DATE('15:00:00', 'HH24:MI:SS'), TO_DATE('16:25:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (154, TO_DATE('15:30:00', 'HH24:MI:SS'), TO_DATE('16:55:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (155, TO_DATE('16:00:00', 'HH24:MI:SS'), TO_DATE('17:25:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (156, TO_DATE('16:30:00', 'HH24:MI:SS'), TO_DATE('17:55:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (157, TO_DATE('17:00:00', 'HH24:MI:SS'), TO_DATE('18:25:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (158, TO_DATE('17:30:00', 'HH24:MI:SS'), TO_DATE('18:55:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (159, TO_DATE('18:00:00', 'HH24:MI:SS'), TO_DATE('19:25:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (160, TO_DATE('18:30:00', 'HH24:MI:SS'), TO_DATE('19:55:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (161, TO_DATE('19:00:00', 'HH24:MI:SS'), TO_DATE('20:25:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (162, TO_DATE('19:30:00', 'HH24:MI:SS'), TO_DATE('20:55:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (163, TO_DATE('20:00:00', 'HH24:MI:SS'), TO_DATE('21:25:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (164, TO_DATE('20:30:00', 'HH24:MI:SS'), TO_DATE('21:55:00', 'HH24:MI:SS'));
INSERT INTO HORARIO (ID_HORARIO, HORA_SALIDA_PROGRAMADA, HORA_LLEGADA_PROGRAMADA) 
VALUES (165, TO_DATE('21:00:00', 'HH24:MI:SS'), TO_DATE('22:25:00', 'HH24:MI:SS'));

-- ASIGNACIONES
-- Asignaciones para rutas 4 y 6, usando horarios 1 al 33
-- Ruta 4 - Trenes 1, 3, 4 alternando
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (1, 1, 4, 1);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (2, 3, 4, 2);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (3, 4, 4, 3);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (4, 1, 4, 4);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (5, 3, 4, 5);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (6, 4, 4, 6);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (7, 1, 4, 7);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (8, 3, 4, 8);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (9, 4, 4, 9);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (10, 1, 4, 10);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (11, 3, 4, 11);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (12, 4, 4, 12);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (13, 1, 4, 13);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (14, 3, 4, 14);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (15, 4, 4, 15);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (16, 1, 4, 16);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (17, 3, 4, 17);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (18, 4, 4, 18);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (19, 1, 4, 19);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (20, 3, 4, 20);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (21, 4, 4, 21);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (22, 1, 4, 22);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (23, 3, 4, 23);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (24, 4, 4, 24);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (25, 1, 4, 25);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (26, 3, 4, 26);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (27, 4, 4, 27);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (28, 1, 4, 28);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (29, 3, 4, 29);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (30, 4, 4, 30);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (31, 1, 4, 31);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (32, 3, 4, 32);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (33, 4, 4, 33);

-- Ruta 6 - Trenes 5, 6, 7 alternando
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (34, 5, 6, 1);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (35, 6, 6, 2);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (36, 7, 6, 3);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (37, 5, 6, 4);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (38, 6, 6, 5);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (39, 7, 6, 6);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (40, 5, 6, 7);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (41, 6, 6, 8);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (42, 7, 6, 9);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (43, 5, 6, 10);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (44, 6, 6, 11);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (45, 7, 6, 12);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (46, 5, 6, 13);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (47, 6, 6, 14);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (48, 7, 6, 15);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (49, 5, 6, 16);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (50, 6, 6, 17);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (51, 7, 6, 18);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (52, 5, 6, 19);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (53, 6, 6, 20);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (54, 7, 6, 21);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (55, 5, 6, 22);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (56, 6, 6, 23);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (57, 7, 6, 24);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (58, 5, 6, 25);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (59, 6, 6, 26);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (60, 7, 6, 27);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (61, 5, 6, 28);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (62, 6, 6, 29);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (63, 7, 6, 30);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (64, 5, 6, 31);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (65, 6, 6, 32);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (66, 7, 6, 33);

-- Ruta 9 - Trenes 8, 9, 10 alternando (horarios 34-66)
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (67, 8, 9, 34);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (68, 9, 9, 35);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (69, 10, 9, 36);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (70, 8, 9, 37);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (71, 9, 9, 38);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (72, 10, 9, 39);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (73, 8, 9, 40);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (74, 9, 9, 41);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (75, 10, 9, 42);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (76, 8, 9, 43);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (77, 9, 9, 44);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (78, 10, 9, 45);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (79, 8, 9, 46);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (80, 9, 9, 47);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (81, 10, 9, 48);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (82, 8, 9, 49);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (83, 9, 9, 50);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (84, 10, 9, 51);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (85, 8, 9, 52);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (86, 9, 9, 53);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (87, 10, 9, 54);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (88, 8, 9, 55);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (89, 9, 9, 56);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (90, 10, 9, 57);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (91, 8, 9, 58);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (92, 9, 9, 59);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (93, 10, 9, 60);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (94, 8, 9, 61);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (95, 9, 9, 62);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (96, 10, 9, 63);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (97, 8, 9, 64);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (98, 9, 9, 65);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (99, 10, 9, 66);

-- Ruta 5 - Trenes 11, 12, 13 alternando (horarios 67-99)
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (100, 11, 5, 67);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (101, 12, 5, 68);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (102, 13, 5, 69);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (103, 11, 5, 70);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (104, 12, 5, 71);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (105, 13, 5, 72);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (106, 11, 5, 73);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (107, 12, 5, 74);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (108, 13, 5, 75);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (109, 11, 5, 76);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (110, 12, 5, 77);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (111, 13, 5, 78);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (112, 11, 5, 79);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (113, 12, 5, 80);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (114, 13, 5, 81);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (115, 11, 5, 82);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (116, 12, 5, 83);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (117, 13, 5, 84);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (118, 11, 5, 85);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (119, 12, 5, 86);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (120, 13, 5, 87);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (121, 11, 5, 88);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (122, 12, 5, 89);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (123, 13, 5, 90);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (124, 11, 5, 91);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (125, 12, 5, 92);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (126, 13, 5, 93);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (127, 11, 5, 94);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (128, 12, 5, 95);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (129, 13, 5, 96);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (130, 11, 5, 97);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (131, 12, 5, 98);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (132, 13, 5, 99);

-- Ruta 10 - Trenes 14, 15, 16 alternando (horarios 100-132)
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (133, 14, 10, 100);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (134, 15, 10, 101);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (135, 16, 10, 102);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (136, 14, 10, 103);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (137, 15, 10, 104);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (138, 16, 10, 105);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (139, 14, 10, 106);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (140, 15, 10, 107);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (141, 16, 10, 108);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (142, 14, 10, 109);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (143, 15, 10, 110);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (144, 16, 10, 111);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (145, 14, 10, 112);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (146, 15, 10, 113);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (147, 16, 10, 114);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (148, 14, 10, 115);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (149, 15, 10, 116);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (150, 16, 10, 117);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (151, 14, 10, 118);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (152, 15, 10, 119);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (153, 16, 10, 120);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (154, 14, 10, 121);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (155, 15, 10, 122);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (156, 16, 10, 123);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (157, 14, 10, 124);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (158, 15, 10, 125);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (159, 16, 10, 126);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (160, 14, 10, 127);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (161, 15, 10, 128);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (162, 16, 10, 129);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (163, 14, 10, 130);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (164, 15, 10, 131);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (165, 16, 10, 132);

-- Ruta 8 - Trenes 17, 24, 25 alternando (horarios 133-165)
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (166, 17, 8, 133);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (167, 24, 8, 134);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (168, 25, 8, 135);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (169, 17, 8, 136);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (170, 24, 8, 137);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (171, 25, 8, 138);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (172, 17, 8, 139);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (173, 24, 8, 140);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (174, 25, 8, 141);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (175, 17, 8, 142);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (176, 24, 8, 143);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (177, 25, 8, 144);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (178, 17, 8, 145);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (179, 24, 8, 146);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (180, 25, 8, 147);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (181, 17, 8, 148);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (182, 24, 8, 149);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (183, 25, 8, 150);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (184, 17, 8, 151);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (185, 24, 8, 152);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (186, 25, 8, 153);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (187, 17, 8, 154);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (188, 24, 8, 155);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (189, 25, 8, 156);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (190, 17, 8, 157);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (191, 24, 8, 158);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (192, 25, 8, 159);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (193, 17, 8, 160);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (194, 24, 8, 161);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (195, 25, 8, 162);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (196, 17, 8, 163);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (197, 24, 8, 164);
INSERT INTO ASIGNACION_TREN (ID_ASIGNACION, ID_TREN, ID_RUTA, ID_HORARIO) VALUES (198, 25, 8, 165);
